// ui/atlas_of_us_ui/src/lib/pages/Login/Login.svelte
<script lang="ts">
  import { API_BASE } from "../../../environment";
  import { goto } from "@mateothegreat/svelte5-router";

  let username = "";
  let password = "";

  async function handleSubmit() {
    console.log("Logging in with:", username, password);
    const response = await fetch(
      `${API_BASE}/api/login`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          username,
          password,
        }),
      }
    );

    if (response.ok) {
      console.log("Logged in successfully");
      const responseBody = await response.json();
      localStorage.setItem("jwt", responseBody);
      goto("/Graph");
    } else {
      console.error("Login failed");
    }
  }
</script>

<div class="in-nav-container">
  <h2>Login</h2>
  <form on:submit|preventDefault={handleSubmit}>
    <label for="username">Username:</label>
    <input type="text" id="username" bind:value={username} />

    <label for="password">Password:</label>
    <input type="password" id="password" bind:value={password} />

    <button type="submit">Login</button>
  </form>
</div>

<style>
  label {
    display: block;
    margin-bottom: 5px;
  }

  input {
    width: 100%;
    padding: 8px;
    margin-bottom: 15px;
    border: 1px solid #ddd;
    border-radius: 4px;
    box-sizing: border-box;
  }

  button {
    background-color: #4caf50;
    color: white;
    padding: 10px 15px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  button:hover {
    background-color: #3e8e41;
  }
</style>

// ui/atlas-of-us-web-ui/src/pages/Login/Login.tsx
import { useState } from "react";
import "./login.css";
import { NavBar } from "../../common-components/navbar/nav";
import { Link, useNavigate } from "react-router";
import { useGlobal } from "../../GlobalProvider";

export function Login() {
  const apiBaseUrl = import.meta.env.VITE_API_BASE_URL;

  const navigate = useNavigate();

  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const { loggedIn, setLoggedIn } = useGlobal();

  async function handleLogin() {
    try {
      const response = await fetch(`${apiBaseUrl}/api/login`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          username,
          password,
        }),
      });

      if (response.ok) {
        console.log("Logged in successfully");
        const responseBody = await response.json();
        localStorage.setItem("jwt", responseBody);
        setLoggedIn(true);
        navigate("/Graph");
      } else {
        console.error("Login failed");
        // Handle login failure (e.g., display an error message)
      }
    } catch (error) {
      console.error("Login error:", error);
      // Handle network errors or other exceptions
    }
  }

  return (
    <>
      <NavBar />
      <div className="in-nav-container">
        <div className="login-container">
          <h1>Welcome Back!</h1>
          <p>Time to see who you are, and who you might become...</p>
          <div className="">
            <label className="" htmlFor="username">
              Username:
            </label>
            <input
              className=""
              id="username"
              type="text"
              placeholder="Username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
            />
          </div>
          <div className="">
            <label className="" htmlFor="password">
              Password:
            </label>
            <input
              className=""
              id="password"
              type="password"
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          <div className="mt-10">
            <button className="aou-button mr-10" type="button" onClick={handleLogin}>
              Sign In
            </button>
            <a className="aou-button" href="#">
              Forgot Password?
            </a>
          </div>
          <div className="or-container">
            <div className="line"></div>
            <div className="or-text">OR</div>
            <div className="line"></div>
          </div>
          <h2>New Here?</h2>
          <Link to="/Create">Create an account</Link> to experience the joy of
          clairvoyance.
        </div>
      </div>
    </>
  );
}
